//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlas.Xml.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must not be empty!.
        /// </summary>
        internal static string ArgumentMustNotBeEmptyExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmptyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument validation failed!.
        /// </summary>
        internal static string ArgumentValidationFailedExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentValidationFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Atlas.Xml;
        ///using System.Xml;
        ///
        ///namespace Atlas.Xml.SerializationCompiler.Dynamic
        ///{
        ///    public class {className} : IXmlSerializer&lt;{typeName}&gt;
        ///    {
        ///
        ///{classLevelCodePart}
        ///		public void Serialize(XmlWriter writer, {typeName} objectInstance, SerializationOptions options)
        ///		{
        /////BEGIN: Remove If Sealed
        ///			var realType =  objectInstance.GetType();
        ///			if(realType != typeof({typeName}))
        ///			{
        ///				writer.WriteAttributeString(Serializer.TypeAttributeName, realType.GetNameForGetType()) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeTemplate {
            get {
                return ResourceManager.GetString("CodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Atlas.Xml;
        ///using System.Xml;
        ///using System.Collections.Generic;
        ///
        ///namespace Atlas.Xml.SerializationCompiler.Dynamic
        ///{
        ///    public class {className} : IXmlSerializer&lt;{typeName}&gt;
        ///    {
        ///
        ///{classLevelCodePart}
        ///		public void Serialize(XmlWriter writer, {typeName} objectInstance, SerializationOptions options)
        ///		{
        ///			foreach (var item in objectInstance)
        ///			{
        ///				writer.WriteStartElement(options.ChildElementName);
        ///{childWriterCode}
        ///                writer.WriteEndElement();
        ///			}
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeTemplateForArray {
            get {
                return ResourceManager.GetString("CodeTemplateForArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Atlas.Xml;
        ///using System.Xml;
        ///
        ///namespace Atlas.Xml.SerializationCompiler.Dynamic
        ///{
        ///    public class {className} : IXmlSerializer&lt;{typeName}&gt;
        ///    {
        ///
        ///{classLevelCodePart}
        ///		public void Serialize(XmlWriter writer, {typeName} objectInstance, SerializationOptions options)
        ///		{
        /////BEGIN: Remove If Sealed
        ///			var realType =  objectInstance.GetType();
        ///			if(realType != typeof({typeName}))
        ///			{
        ///				writer.WriteAttributeString(Serializer.TypeAttributeName, realType.GetNameForGetType()) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeTemplateForEnumerable {
            get {
                return ResourceManager.GetString("CodeTemplateForEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Atlas.Xml;
        ///using System.Xml;
        ///
        ///namespace Atlas.Xml.SerializationCompiler.Dynamic
        ///{
        ///    public class {className} : IXmlSerializer&lt;{typeName}&gt;
        ///    {
        ///
        ///{classLevelCodePart}
        ///		public void Serialize(XmlWriter writer, {typeName} objectInstance, SerializationOptions options)
        ///		{
        ///{writerCode}
        ///		}
        ///
        ///		public {typeName} Deserialize(XmlReader reader, SerializationOptions options)
        ///		{
        ///			var objectInstance = default({typeName});
        ///
        ///			if(!reader.IsEmptyElement)
        ///			{
        ///				while (reader [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeTemplateForValueType {
            get {
                return ResourceManager.GetString("CodeTemplateForValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization into instance for type {0} is not supported!.
        /// </summary>
        internal static string DeserializeIntoNotSupportedForTypeExceptionMessage {
            get {
                return ResourceManager.GetString("DeserializeIntoNotSupportedForTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Dictionary child element is missing it&apos;s key attribute..
        /// </summary>
        internal static string XmlMissingDictionaryKeyAttributeExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingDictionaryKeyAttributeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Dictionary child element is missing it&apos;s key element..
        /// </summary>
        internal static string XmlMissingDictionaryKeyElementExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingDictionaryKeyElementExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Dictionary child element is missing it&apos;s value attribute..
        /// </summary>
        internal static string XmlMissingDictionaryValueAttributeExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingDictionaryValueAttributeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Dictionary child element is missing it&apos;s value element..
        /// </summary>
        internal static string XmlMissingDictionaryValueElementExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingDictionaryValueElementExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Dictionary child element is missing it&apos;s value text..
        /// </summary>
        internal static string XmlMissingDictionaryValueTextExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingDictionaryValueTextExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Xml element is missing it&apos;s value attribute..
        /// </summary>
        internal static string XmlMissingValueAttributeExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingValueAttributeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Xml element is missing it&apos;s value element..
        /// </summary>
        internal static string XmlMissingValueElementExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingValueElementExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Xml element is missing it&apos;s value text..
        /// </summary>
        internal static string XmlMissingValueTextExceptionMessage {
            get {
                return ResourceManager.GetString("XmlMissingValueTextExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize type: &apos;{0}&apos;! Xml element is missing it&apos;s type declaration (e.g.: first attribute with name: &apos;{1}&apos;).
        /// </summary>
        internal static string XmlTypeAttributeMissingExceptionMessage {
            get {
                return ResourceManager.GetString("XmlTypeAttributeMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type &apos;{0}&apos; is not supported for serialization! Only fields and properties can be serialized..
        /// </summary>
        internal static string XmlUnsupportedMemberTypeExceptionMessage {
            get {
                return ResourceManager.GetString("XmlUnsupportedMemberTypeExceptionMessage", resourceCulture);
            }
        }
    }
}
